title: kellsaro on tech
description: > # this means to ignore newlines until "baseurl:"
  Hi there, I'm Maykell Sánchez Romero, a software developer, and this is my blog.
  I write about programming languages, frameworks, technics... technology in general.
permalink: ':title/'
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: # Add the site's Twitter

# Author Settings
author: Maykell Sánchez Romero # add your name
author-img: kellsaro.jpg # add your photo
about-author: I'm Full Stack Web Developer interested in happy programming and productivity being in the Zone. Always hungry to keep learning. May the Flow be with you. # add description
social-twitter: kellsaro
social-facebook: kellsaro
social-github: kellsaro # add your Github handle
social-linkedin: kellsaro
social-email: kellsaro@gmail.com

# Disqus
discus-identifier: kellsaro # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
